branch-defaults:
  boardsizing:
    environment: null
    group_suffix: null
  codecommit:
    environment: otterio-production-env
    group_suffix: null
  master:
    environment: OtterIO-2
    group_suffix: null
environment-defaults:
  OtterIO:
    branch: master
    repository: thesis
  OtterIO-2:
    branch: master
    repository: thesis
  OtterIO-production:
    branch: null
    repository: null
  Otterio-production:
    branch: master
    repository: thesis
global:
  application_name: Otter.IO
  branch: master
  default_ec2_keyname: aws-keypair
  default_platform: Node.js
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: thesis
  sc: git
  workspace_type: Application
