branch-defaults:
  boardsizing:
    environment: null
    group_suffix: null
  codecommit:
    environment: otterio-production-env
    group_suffix: null
global:
  application_name: Otter.io
  branch: null
  default_ec2_keyname: aws-keypair
  default_platform: Node.js
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
